[package]
name = "arukas"
version = "0.1.0"
authors = ["shiinamiyuki <xiaochun.tong@mail.utoronto.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.21.0"
vulkano-win = "0.21.0"
vulkano-shaders = "0.21.0"
winit = "0.24"
nalgebra = "0.25.3"
nalgebra-glm = "0.11.0"
tobj = "2.0.4"